server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pool
    username: change_me_username
    password: change_me_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update