version: "3.9"
services:
  configuration-server:
    build: ./configuration-server/
    ports:
      - "8888:8888"
    restart: always
  discovery-service:
    build: ./discovery-service/
    depends_on:
      - configuration-server
    ports:
      - "8761:8761"
    restart: always
  gateway-server:
    build: ./gateway-server/
    depends_on:
      - configuration-server
      - discovery-service
    ports:
      - "8072:8072"
    restart: always
  pool-service:
    build: ./pool-service/
    depends_on:
      - postgres
      - configuration-server
      - discovery-service
    restart: always
  results-service:
    build: ./results-service/
    depends_on:
      - configuration-server
      - discovery-service
    restart: always
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      - 'POSTGRES_DB=pool'
      - 'POSTGRES_PASSWORD=pgadmin'
      - 'POSTGRES_USER=pool'
    ports:
      - "5432:5432"
  #    volumes:
  #      - "./<your_sql_file_name_here>.sql:/docker-entrypoint-initdb.d/1.sql"