server:
  port: 8888
spring:
  application:
    name: configuration-server
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          searchLocations: file:///config/
        git:
          uri: https://github.com/DawidStankiewicz/microservices-java-example
          searchPaths: configuration/pool-service
          default-label: master