apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: configuration-server
  name: configuration-server
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: configuration-server

