apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: discovery-service
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-service
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/microservices-java-example-default: "true"
        io.kompose.service: discovery-service
    spec:
      containers:
        - image: discovery-service
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8761/actuator/health
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
          name: discovery-service
          ports:
            - containerPort: 8761
              hostPort: 8761
              protocol: TCP
          resources: {}
      restartPolicy: Always
