apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gateway-server
  name: gateway-server
spec:
  ports:
    - name: "8072"
      port: 8072
      targetPort: 8072
  selector:
    io.kompose.service: gateway-server
  type: LoadBalancer
