apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/microservices-java-example-default: "true"
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: pool
            - name: POSTGRES_PASSWORD
              value: pgadmin
            - name: POSTGRES_USER
              value: pool
          image: postgres:16.4
          livenessProbe:
            exec:
              command:
                - pg_isready -U pool -d pool
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
      restartPolicy: Always
