apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: results-service
  name: results-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: results-service
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/microservices-java-example-default: "true"
        io.kompose.service: results-service
    spec:
      containers:
        - image: results-service
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8081/actuator/health
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
          name: results-service
          resources: {}
      restartPolicy: Always
