version: "3.9"
services:
  postgres:
    image: postgres:16.4
#    image: postgres:latest
    restart: always
    environment:
      - 'POSTGRES_DB=pool'
      - 'POSTGRES_PASSWORD=pgadmin'
      - 'POSTGRES_USER=pool'
    ports:
      - "5432:5432"
#    volumes:
#      - "./<your_sql_file_name_here>.sql:/docker-entrypoint-initdb.d/1.sql"